export const cardsData = [
  {
      id: 1,
      title: "Card 1",
      datatime: "19/05/2022 10:48 hs.",
      creator: "Pablo Tachella",
      description: "Reemplazar por descripción de la tarjeta",
      type: "new",
      priority: "high",
  },
  {
      id: 2,
      title: "Card 2",
      datatime: "19/05/2022 10:48 hs.",
      creator: "Pablo Tachella",
      description: "Reemplazar por descripción de la tarjeta",
      type: "new",
      priority: "high",
  },
  {
      id: 3,
      title: "Card 3",
      datatime: "19/05/2022 10:48 hs.",
      creator: "Pablo Tachella",
      description: "Reemplazar por descripción de la tarjeta",
      type: "new",
      priority: "high",
  },
  {
      id: 4,
      title: "Card 4",
      datatime: "19/05/2022 10:48 hs.",
      creator: "Pablo Tachella",
      description: "Reemplazar por descripción de la tarjeta",
      type: "new",
      priority: "high",
  },
  {
      id: 5,
      title: "Card 5",
      datatime: "19/05/2022 10:48 hs.",
      creator: "Pablo Tachella",
      description: "Reemplazar por descripción de la tarjeta",
      type: "new",
      priority: "high",
  },
  {
      id: 6,
      title: "Card 6",
      datatime: "19/05/2022 10:48 hs.",
      creator: "Pablo Tachella",
      description: "Reemplazar por descripción de la tarjeta",
      type: "new",
      priority: "high",
  },
]